<div class="well">
	    <h3>Add ingredient to pizza</h3>
	    
	    <?php echo $this->form_ingredients_add ?>
	    
</div>


<hr>
	<a href="<?php echo $this->url(
		    array(
		        'controller' => 'pizza',
		        'action'     => 'index'
		    ),
		    'default',
	    	true) ?>">listing</a> - 
	<a href="<?php echo $this->url(
		    array(
		        'controller' => 'pizza',
		        'action'     => 'edit',
		        'id'		 => $this->pizza->id
		    ),
		    'default',
	    	true) ?>">edit</a> -

	<a href="<?php echo $this->url(
		    array(
		        'controller' => 'pizza',
		        'action'     => 'delete',
		        'id'		 => $this->pizza->id
		    ),
		    'default',
	    	true) ?>" onClick="return confirm('Are you sure you want to delete the pizza?')">delete</a>

<hr>