<div class="well">
		<p>#<?php echo $this->escape($this->pizza->id) ?> </p>
	    <h3>Edit pizza</h3>
	    
	    <?php echo $this->form ?>
</div>

<hr/>

<div class="well">
		<script>
			//var listing = [12, 14, 20];
		</script>
	    <h3>Current ingredients <small>(Section under construction)</small></h3>
	    
	    <?php //echo $this->form_ingredients ?>

	    <?php if(count($this->allPizzaIngredients) > 0): ?>

			<ol class="ol-horizontal">

				<?php foreach ($this->allPizzaIngredients as $entry): ?>

					<li>
						<?php echo $this->escape($entry->ingredient_name) ?>: <?php echo $this->escape($entry->quantity) ?> gr
						
						-   <a href="<?php echo $this->url(
								    array(
								        'controller' => 'pizza',
								        'action'     => 'delete2',
								        'id'		 => $this->pizza->id
								    ),
								    'default',
					    	true) ?>" onClick="return confirm('Are you sure you want to delete the pizza?')">delete</a>
					</li>

				<?php endforeach; ?>	

			</ol>

		<?php else: ?>

			This pizza has no ingredients yet.

		<?php endif; ?>
</div>

<hr/>

<div class="well">
	    <h3>Add ingredient to pizza</h3>
	    
	    <?php echo $this->form_ingredients_add ?>
</div>


<hr>
	<a href="<?php echo $this->url(
		    array(
		        'controller' => 'pizza',
		        'action'     => 'index'
		    ),
		    'default',
	    	true) ?>">listing</a> - 
	<a href="<?php echo $this->url(
		    array(
		        'controller' => 'pizza',
		        'action'     => 'edit',
		        'id'		 => $this->pizza->id
		    ),
		    'default',
	    	true) ?>">edit</a> -

	<a href="<?php echo $this->url(
		    array(
		        'controller' => 'pizza',
		        'action'     => 'delete',
		        'id'		 => $this->pizza->id
		    ),
		    'default',
	    	true) ?>" onClick="return confirm('Are you sure you want to delete the pizza?')">delete</a>

<hr>

