<div class="well">
		<p>#<?php echo $this->escape($this->pizza->id) ?> </p>
	    <h3>Edit pizza</h3>
	    
	    <?php echo $this->form ?>
</div>

<hr/>

<div class="well">
		<script>
			//var listing = [12, 14, 20];
		</script>
	    <h3>Current ingredients <small>(Section under construction)</small></h3>
	    
	    <?php //echo $this->form_ingredients ?>

	    <?php if(count($this->allPizzaIngredients) > 0): ?>

			<ol class="ol-horizontal" id="sortableIngredients">

				<?php foreach ($this->allPizzaIngredients as $entry): ?>

					<li class="ui-state-default" data-id="<?php echo $this->escape($entry->id) ?>">
						<span class="ui-icon ui-icon-arrowthick-2-n-s"></span>
						<?php echo $this->escape($entry->ingredient_name) ?>: <?php echo $this->escape($entry->quantity) ?> gr (<?php echo $this->escape($entry->ordering) ?>)
						
						-   <a href="<?php echo $this->url(
								    array(
								        'controller' 	=> 'pizza',
								        'action'     	=> 'deleteingredient',
								        'id'		 	=> $entry['id'],
								    ),
								    'default',
					    	true) ?>" onClick="return confirm('Are you sure you want to delete the pizza?')">delete</a>
					</li>

				<?php endforeach; ?>	

			</ol>

		<?php else: ?>

			This pizza has no ingredients yet.

		<?php endif; ?>
</div>

<hr/>

<div class="well">
	    <h3>Add ingredient to pizza</h3>
	    
	    <?php //echo $this->form_ingredients_add ?>
	    <a href="<?php echo $this->url(
		    array(
		        'controller' => 'pizza',
		        'action'     => 'addingredient',
		        'pizza_id'		 => $this->pizza->id
		    ),
		    'default',
	    	true) ?>" class="btn btn-primary">Add</a>
</div>


<hr>
	<a href="<?php echo $this->url(
		    array(
		        'controller' => 'pizza',
		        'action'     => 'index'
		    ),
		    'default',
	    	true) ?>">listing</a> - 
	<a href="<?php echo $this->url(
		    array(
		        'controller' => 'pizza',
		        'action'     => 'edit',
		        'id'		 => $this->pizza->id
		    ),
		    'default',
	    	true) ?>">edit</a> -

	<a href="<?php echo $this->url(
		    array(
		        'controller' => 'pizza',
		        'action'     => 'delete',
		        'id'		 => $this->pizza->id
		    ),
		    'default',
	    	true) ?>" onClick="return confirm('Are you sure you want to delete the pizza?')">delete</a>

<hr>

